name = "DifferentialDynamicProgramming"
uuid = "9cd584b6-1a68-5b24-b787-24af5fbbf48b"
author = "Fredrik Bagge Carlson <baggepinnen@gmail.com>"
repo = "https://github.com/baggepinnen/DifferentialDynamicProgramming.jl.git"

[deps]
LTVModelsBase = "52bd5b67-3fca-59a1-821b-f5f08aa0287b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ValueHistories = "98cad3c8-aec3-5f06-8e41-884608649ab7"
